const express=require('express')
const path=require('path')
const app=express()
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/',express.static(path.join(__dirname,'public')))
app.use('/cost',require('./routes/cost').route)
app.use('/api',require('./routes/passangar').route)
app.listen(5000,()=>console.log("server started"))